### ISSUE TITLE
Polyphonic trigger output for ntrvlc expander

### ISSUE THREAD

**Issue by vcvrackideas** [Lyqst/cvly-modules#2]
Hi! Thanks for these awesome modules! I'm wondering if you have a room and wish to add poly out triggers in your new expander?
Would be great for combining both poly cv and poly trigger output into the one poly synth voice. Cheers!

**Comment by Lyqst** [comment]
Hey, thanks for the kind words! I decided against it due to space, but now I'm thinking about adding an option in the context menu to turn the first output into a poly one, that way I don't have to accommodate an extra output, would that work for you?

**Comment by vcvrackideas** [comment]
Yes, would be great option! Thanks

**Comment by Lyqst** [comment]
Done ca83efa8be22c6ad0839a19e4322218761c76238
