### ISSUE TITLE
Binaries committed to repository

### ISSUE THREAD

**Issue by cschol** [Lyqst/cvly-modules#3]
Binaries (`plugin.dll`) have been committed to the repository. These will increase the repository size over time. Since the build process clones the repository fresh every time it will increase the bandwidth needs for the build process. We ask that you please remove the binaries from the repository.

Note, that a commit s **not enough** to remove the binaries. You will need to remove them from the repository history also. You can either recreate the repository without the binaries and repush or use a tool like [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove the binaries. 

Thank you!

**Comment by Lyqst** [comment]
Thanks for the info! Cleaned using BFG.
