### ISSUE TITLE
ntrvlc UI cut off

### ISSUE THREAD

**Issue by SteveRussell33** [Lyqst/cvly-modules#4]
![ntrvlc](https://user-images.githubusercontent.com/41975381/129729143-f1518c8b-352d-4c5d-9916-e889954b8c3c.png)

Problem is due to commit f831b8b9ac371da24b943f9a1e9ded1d8da58928
https://github.com/Lyqst/cvly-modules/blob/f831b8b9ac371da24b943f9a1e9ded1d8da58928/res/ntrvlc.svg#L10-L12
The original values were: ```width="142.24001mm"``` ```viewBox="0 0 142.24 128.5"```

**Comment by Lyqst** [comment]
Thanks for pointing that out, don't know how I missed it
