### ISSUE TITLE
Request: Poly gate input into bss

### ISSUE THREAD

**Issue by Rcomian** [Lyqst/cvly-modules#7]
Or some other method of solving this issue:

If I've got a midi module set to 4 way polyphony, and play a 3 note chord, bss is trying to guess the root note from a 4 note chord, and the 4th note is just whatever was left over from the previous playing.

This means a different root note can be played even if you play the same chord twice in a row.
If bss took a poly gate input as well, it could determine which of the inputs to actually consider - then it would work for however many notes were actually in the chord being played.

**Comment by Lyqst** [comment]
That's a great idea, will look into it!

**Comment by Lyqst** [comment]
Comes along with the update for v2
