### ISSUE TITLE
update for V2

### ISSUE THREAD

**Issue by rsmus7** [Lyqst/cvly-modules#8]
Hi Benja, 
thanks for your modules I like them very much,
will you update them for Rack V2?

**Comment by Lyqst** [comment]
Hey! Glad to hear that.

I've been a little busy lately with other stuff, but I'm working now on updating the modules for Rack V2 (along with a small GUI rework). Should be available in a couple of days.

**Comment by vcvrackideas** [comment]
Hi Benja, still not v2 ready I suppose? Sorry for bothering you anyway ;-)

**Comment by Lyqst** [comment]
I finally did it!
